hotels = [
    {"id": 1, "name": "Hotel Copacabana", "city": "Rio de Janeiro", "address": "Av. Atlântica, 1234", "stars": 4, "phone": "+55 21 1234-5678", "email": "contato@hotelcopacabana.com", "website": "https://hotelcopacabana.com"},
    {"id": 2, "name": "Hotel Ipanema", "city": "Rio de Janeiro", "address": "Rua Visconde de Pirajá, 500", "stars": 5, "phone": "+55 21 9876-5432", "email": "contato@hotelipanema.com", "website": "https://hotelipanema.com"},
    {"id": 3, "name": "Hotel Paulista", "city": "São Paulo", "address": "Av. Paulista, 2000", "stars": 3, "phone": "+55 11 3333-4444", "email": "contato@hotelpaulista.com", "website": "https://hotelpaulista.com"},
    {"id": 4, "name": "Hotel Recife", "city": "Recife", "address": "Av. Boa Viagem, 1500", "stars": 4, "phone": "+55 81 4444-5555", "email": "contato@hotelrecife.com", "website": "https://hotelrecife.com"},
    {"id": 5, "name": "Hotel Salvador", "city": "Salvador", "address": "Rua das Flores, 100", "stars": 3, "phone": "+55 71 5555-6666", "email": "contato@hotelsalvador.com", "website": "https://hotelsalvador.com"},
    {"id": 6, "name": "Hotel Brasília", "city": "Brasília", "address": "Esplanada dos Ministérios, 1", "stars": 4, "phone": "+55 61 7777-8888", "email": "contato@hotelbrasilia.com", "website": "https://hotelbrasilia.com"},
    {"id": 7, "name": "Hotel Curitiba", "city": "Curitiba", "address": "Rua XV de Novembro, 250", "stars": 3, "phone": "+55 41 2222-3333", "email": "contato@hotelcuritiba.com", "website": "https://hotelcuritiba.com"},
    {"id": 8, "name": "Hotel Fortaleza", "city": "Fortaleza", "address": "Av. Beira Mar, 789", "stars": 4, "phone": "+55 85 8888-9999", "email": "contato@hotelfortaleza.com", "website": "https://hotelfortaleza.com"},
    {"id": 9, "name": "Hotel Manaus", "city": "Manaus", "address": "Av. Eduardo Ribeiro, 456", "stars": 3, "phone": "+55 92 4444-5555", "email": "contato@hotelmanaus.com", "website": "https://hotelmanaus.com"},
    {"id": 10, "name": "Hotel Porto Alegre", "city": "Porto Alegre", "address": "Rua dos Andradas, 1000", "stars": 4, "phone": "+55 51 3333-2222", "email": "contato@hotelportoalegre.com", "website": "https://hotelportoalegre.com"},
    {"id": 11, "name": "Hotel Florianópolis", "city": "Florianópolis", "address": "Av. Beira Mar Norte, 150", "stars": 4, "phone": "+55 48 9999-8888", "email": "contato@hotelflorianopolis.com", "website": "https://hotelflorianopolis.com"},
    {"id": 12, "name": "Hotel Natal", "city": "Natal", "address": "Praia de Ponta Negra, 321", "stars": 3, "phone": "+55 84 7777-6666", "email": "contato@hotelnatal.com", "website": "https://hotelnatal.com"},
    {"id": 13, "name": "Hotel Belém", "city": "Belém", "address": "Av. Presidente Vargas, 888", "stars": 3, "phone": "+55 91 3333-4444", "email": "contato@hotelbelem.com", "website": "https://hotelbelem.com"},
    {"id": 14, "name": "Hotel João Pessoa", "city": "João Pessoa", "address": "Av. Epitácio Pessoa, 456", "stars": 4, "phone": "+55 83 2222-1111", "email": "contato@hoteljoaopessoa.com", "website": "https://hoteljoaopessoa.com"},
    {"id": 15, "name": "Hotel Campinas", "city": "Campinas", "address": "Rua 13 de Maio, 250", "stars": 3, "phone": "+55 19 5555-4444", "email": "contato@hotelcampinas.com", "website": "https://hotelcampinas.com"},
    {"id": 16, "name": "Hotel Santos", "city": "Santos", "address": "Av. Ana Costa, 123", "stars": 4, "phone": "+55 13 7777-8888", "email": "contato@hotelsantos.com", "website": "https://hotelsantos.com"},
    {"id": 17, "name": "Hotel Ribeirão Preto", "city": "Ribeirão Preto", "address": "Rua Álvares Cabral, 900", "stars": 3, "phone": "+55 16 3333-2222", "email": "contato@hotelribeiraopreto.com", "website": "https://hotelribeiraopreto.com"},
    {"id": 18, "name": "Hotel São Luís", "city": "São Luís", "address": "Av. dos Holandeses, 100", "stars": 4, "phone": "+55 98 4444-5555", "email": "contato@hotelsaoluis.com", "website": "https://hotelsaoluis.com"},
    {"id": 19, "name": "Hotel Vitória", "city": "Vitória", "address": "Rua Sete de Setembro, 789", "stars": 4, "phone": "+55 27 6666-7777", "email": "contato@hotelvitoria.com", "website": "https://hotelvitoria.com"},
    {"id": 20, "name": "Hotel Maringá", "city": "Maringá", "address": "Av. Brasil, 456", "stars": 3, "phone": "+55 44 3333-4444", "email": "contato@hotelmaringa.com", "website": "https://hotelmaringa.com"}
]
